version: 2.1
orbs:
  node: node@v12.15.0


jobs:
  build-and-test:
    executor:
      name: node
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test
workflows:
    build-and-test:
      jobs:
        - build-and-test
